package Pojo;

import Pojo.DetilPojo.Education;
import Pojo.DetilPojo.ExpLocation;
import Pojo.DetilPojo.Living;
import Pojo.DetilPojo.Score;

import java.util.ArrayList;

/**
 * Created by Administrator on 2015/4/27.
 */
public class ResumeDetil {
    String accountStatus;
    String active;
    String addTime;
    int alertSendTime;
    int alertSendToCsTime;
    int appTime;
    int autoRefresh;
    String birthday;
//    Null certs;
    String classify;
    String cnName;
    String completed;
    String contactAlert;
    String cvName;
    String degreeId;
    String degreeName;
    String del;
    int delTime;
    int downloads;
    ArrayList<Education> education = new ArrayList();
    String email;
    String enCV;
    String enName;
    String expComTypeId;
    String expComTypeName;
    ArrayList<String> expJobName = new ArrayList<>();
    String expJobTypeId;
    String expJobTypeName;
//    ArrayList<> expJobs = new ArrayList<>();
    ArrayList<ExpLocation> expLocation = new ArrayList<>();
    String expSalary;
    ArrayList<ExpLocation> experience = new ArrayList<>();
    int fails;
    String fileVerified;
    String gender;
    int height;
    int hiddenMonth;
    String id;
    String idName;
    String idNumbers;
    String idType;
    String isActive;
    String isAutoRefresh;
    String isCompleted;
    String isDel;
    String isEnCV;
    String isFileVerified;
    String isLock;
    String isOverseas;
    String isRemind;
    String isTrust;
    int isWork;
    int lLogin;
    int lModTime;
    int lRefTime;
    String lang;
    int lastModTime;
    Living living = new Living();
    String lock;
    int loginSRC;
    String mark;
    String marry;
    String mobile;
//    Null nation;
    String nationId;
    String nationality;
    String nationalityId;
    String negotiation;
    String onboardTime;
//    Null otherInfo;
    String overseas;
    int percent;
    String phone;
    String photoPath;
    int point;
//    ArrayList<> production = new ArrayList<>();
//    Null projects;
    String qq;
    String ranks;
    int regTime;
    String remind;
    String resumeId;
    Score score = new Score();
    String selfEval;
    String site;
    String source;
    String status;
    String title;
    String trust;
    int trustTime;
    String uName;
    String uid;
    String unCheckReason;
    int userDelTime;
    String userIsDel;
    String verified;
    int verifyTime;
    int views;
    String visibility;
    int weight;
    int work;
    String workStatus;
    String workTime;
    String years;
    String yearsId;
    String cvId;
    Boolean isFav;
    String apid;
    String isContact;
    String card_number;
    String addr;
    String zipCode;
    String msn;
    String skype;
    String fetion;
    String webSite;
    String last_refreshed;
    String rank;
//    Null expIndustry;
//    Null training;
//    Null skills;
//    Null works;
    String iterator;
    int isdelete;
}
